### ISSUE TITLE
Setting up Backend 

### ISSUE THREAD

**Issue by shubhamcodez** [shubhamcodez/OpenMeme#13]
Setting up a Backend using Node.js and Express.
Template of the previous backend is already there.
We intend to finish before the end of October.

**Comment by akshay782** [comment]
Hi,
this is a very interesting project but
I could not find the previous backend
So I made one
![open-meme-backend](https://user-images.githubusercontent.com/68458601/135762226-62af349a-35e5-4d54-852b-e81521eb4ac0.png)

I think this will be fine for a starting point since I could not understand some in your project
if you assign me this I will provide a boilerplate / folder structure for the backend

**Comment by akshay782** [comment]
by boilerplate means schemas for those models and routes of user model, 
it will solve you this issue https://github.com/shubhamcodez/OpenMeme/issues/5
but I, unfortunately, I can't help you with Creating Login and Signup Page

**Comment by shubhamcodez** [comment]
That's would be great. 
Setting up of Meme model can be done.

Instead of user sign up,
We can give an input field for user login/ form 
You can refer https://memextream.netlify.app/
To see how we had implement name and comment using form. 

Thanks for the effort, Happy to have received your help.
